# Ch02. Variable

**자료형의 종류**:
- string
- float
- integer
- boolean

## 2.1 할당

In [90]:
#여러 이름 동시에 할당 가능
two = deux = dos = 2              # dos -> deux -> two

print()
print(f'two:  {two},  {id(two)}')      # 메모리 주소값은 동일하다.
print(f'deux: {deux},  {id(deux)}')
print(f'dos:  {dos},  {id(dos)}')


two:  2,  2011984259408
deux: 2,  2011984259408
dos:  2,  2011984259408


<br><br>
## 2.2 가변객체, 불변객체

#### **# 불변객체**

In [87]:
deux = 4           # two, dos는 그대로, deux만 변동 : integer 는 불변객체.

print(f'''
two: {two}, id: {id(two)}
deux:{deux}, id: {id(deux)}
dos: {dos}, id: {id(dos)}
''')


two: 2, id: 2011984259408
deux:4, id: 2011984259472
dos: 2, id: 2011984259408



→ deux가 새로운 값을 할당받는 순간 새로운 메모리 주소를 부여받았다. (수정 x)

#### **# 가변객체**

In [124]:
tempList = [1, 2, 3]
copiedList = tempList

print()
print(f'tempList:   {tempList}, id: {id(tempList)}')
print(f'copiedList: {copiedList}, id: {id(copiedList)}',end='\n\n')

print('copiedList[0] = 5',end='\n\n')
copiedList[0] = 5

print(f'tempList:   {tempList}, id: {id(tempList)}')
print(f'copiedList: {copiedList}, id: {id(copiedList)}',end='\n\n') 


tempList:   [1, 2, 3], id: 2012077913792
copiedList: [1, 2, 3], id: 2012077913792

copiedList[0] = 5

tempList:   [5, 2, 3], id: 2012077913792
copiedList: [5, 2, 3], id: 2012077913792



1. copiedList의 요소값이 변경되었으나 tempList에도 영향을 미친다.  
2. 요소가 변경됐음에도 메모리 주소값은 변동이 없었다.  
→ copiedList와 tempList가 메모리 주소값을 공유하고 있다.

정리)
- 불변객체: 객체에 할당된 값 수정 불가
- 가변객체: 객체에 할당된 값 수정 가능

<br><br>
## 2.3 좋은 변수명

1. 간결, 명확한 이름
2. 의미가 담겨야 함.  
ex) a, b, c, → 무슨 용도로 쓰이는지 이름으로 파악하기 어렵다.<br><br>
ex) the number of students n명의 변수명 설정:  
    - the _number_of_studentsㅤ → 너무 길고, 길어서 오타가 날 수 있다.
    - num_students ㅤㅤㅤㅤㅤㅤ→ 파이썬에서 자주 쓰이는 방식
    - numStudentsㅤㅤㅤㅤㅤㅤㅤ→ Java에서 선호, 캐멀표기법

ㅤcf) 코드에는 의미, 주석에는 의도가 담긴다.


<br><br>
## 2.4 자료형 변환, 형 변환

#### **# 자료형 변환**

In [130]:
a = 10
print('a = 10',end='\n\n')

# str
print(str(a), type(str(a)))

# float
print(float(a), type(float(a)))

# bool
print(bool(a), type(bool(a)))  # 어떤 값이 False로 변환이 되는지 주의한다.

print('\n\n')

a = 10

10 <class 'str'>
10.0 <class 'float'>
True <class 'bool'>





In [123]:
x = 10.7      # x=10.7 공백 붙이는 습관은 좋지 않다.
y = 19.8
print(f'x: {x}, y: {y}',end='\n\n')

print(f'int(x + y)      : {int(x + y)}')
print(f'int(x) + int(y) : {int(x) + int(y)}')

x: 10.7, y: 19.8

int(x + y)      : 30
int(x) + int(y) : 29


- int(x + y)ㅤㅤ== ㅤint(10.7 + 19.8)ㅤㅤ== ㅤint(30.5)ㅤㅤ ㅤ ==ㅤ30  
- int(x) + int(y) == ㅤint(10.7) + int(19.8) == ㅤint(10) + int(19) ==ㅤ29
<br><br>

#### **# 타입에 맞는 형 변환**

##### Correct:

In [141]:
i = '10'
float(i), int(i)

(10.0, 10)

##### Wrong:

In [138]:
j = '10.7'
float(j), int(j)

ValueError: invalid literal for int() with base 10: '10.7'

ㅤ  
string의 내용이 의미하고자 하는 값만 본다면 :  
i = '10'일때 i가 int 10 이나 float 10.0이 되었든 두 자료형 모두 동일한 값을 지닌다.  
하지만 j = '10.7'일 경우 float 10.7과는 동일하나 int(10.7) == 10 과는 동일한 값이라고 할 수 없다.  
ㅤ  
따라서 string을 int나 float으로 형 변환 시 타입에 어긋나지 않는 형 변환을 해야 한다.

<br><br>
## 2.5 `print()`

#### **# 한 줄로 출력**

In [160]:
choco = 'choco'
mint = 'mint'
banana = 'banana'

print(choco + mint + banana) # space X, \n (문자열에 바로 붙인다)
print(choco, mint, banana)   # space O, \n (공백을 자동으로 넣어준다)

chocomintbanana
choco mint banana


ㅤ 
#### **# 한 줄로 코드 작성**

In [161]:
# 코드가 줄이 짧을 때 ; (semicolon) 을 이용해 한 줄로 쓸 수 있다.

choco = 'choco'; mint = 'mint'; banana = 'banana'
print(choco, mint, banana)

choco mint banana


ㅤ 
#### **# 키워드 인수**
- sep=''
- end=''

In [153]:
print(choco, mint, banana, sep=' ', end='\n') # default (기본적으로 end에 '\n'값이 할당된다)
print(choco, mint, banana, sep='/', end='\n\n')
print('EOL')

choco mint banana
choco/mint/banana

EOL


ㅤ 
#### **# 출력 방식의 차이**

In [156]:
#1.
print("My favorite flavor is", mint + '.')

#2.
print(f"My favorite flavor is {mint}.")

My favorite flavor is mint.
My favorite flavor is mint.


ㅤ   
1번 방식: String Concatenation  
2번 방식: Formatted String Literals (f-string)

<br><br>
## 2.6 `input()`

**console에서 사용자가 입력하는 값을 받을 수 있는 함수**
ㅤ  
ㅤ    
#### **# 기본 입력 자료형**
-  입력 받는 값은 기본적으로 문자열 자료형이다. 

In [163]:
userInput = input("숫자를 입력하세요: ")
print(f'userInput은 {type(userInput)}입니다.')

숫자를 입력하세요:  2


userInput은 <class 'str'>입니다.


ㅤ 
#### **# 변수 입력 할당**
-  입력 받은 값을 변수에 할당하여 사용한다.  
   (변수에 할당하지 않는다면 사라지기 때문에 값을 다시 참조할 수 없다.)

In [173]:
# 1번 방식
userName = input("Enter your name:")
print(f'Hello {userName}')
print()

Enter your name: Gandalf


Hello Gandalf



In [176]:
# 2번 방식
print("Enter your name:");
userName = input()

print(f'Hello {userName}')

Enter your name:


 Gandalf


Hello Gandalf


ㅤ 
#### **# 입력 숫자 형 변환**
-  숫자를 입력받고 싶을 경우 형 변환을 한다.  

In [166]:
userInput = int(input("숫자를 입력하세요: "))
print(f'userInput은 {type(userInput)}입니다.')

숫자를 입력하세요:  2


userInput은 <class 'int'>입니다.


<br><br>
## 2.7 *Review*

### # Quiz 1
- 섭씨를 입력 받아서 화씨로 변환하기
- "섭씨 * 1.8 + 32 = 화씨"

In [179]:
celsius = float(input("섭씨:"))
fahren = celsius * 1.8 + 32
print(f'화씨: {celsius} * 1.8 + 32 = {fahren}')

섭씨: 30


화씨: 30.0 * 1.8 + 32 = 86.0


ㅤ 
### # Quiz 2
- 택배 정보 입력 받고(이름, 주소, 무게), 총 합계 계산하기
- 출력값:
    - "==택배 정보=="
    - 수취인 성명: <이름>
    - 수취인 주소: <주소>
    - 배송비: 3000원
    - 물건 비용: <가격>원
    - 총 합계: <가격>원
- 물건 비용 = 무게(g) * 5
- 합계 = 배송비 + 물건 비용

In [180]:
name = input("수취인 성명:")
address = input("수취인 주소:")
weight = float(input("물건 무게:"))

charge = 3000
price = weight * 5
totalCost = charge + price

print()
print(f"""==택배 정보==
수취인 성명: {name}
수취인 주소: {address}
배송비: {charge}원
물건 비용: {price}원
총 합계: {totalCost}원""")

수취인 성명: Santa
수취인 주소: North Pole
물건 무게: 30



==택배 정보==
수취인 성명: Santa
수취인 주소: North Pole
배송비: 3000원
물건 비용: 150.0원
총 합계: 3150.0원


---

# Ch03. Numbers

## 3.1 Boolean

- 조건식에서 많이 쓴다. 
ex) 만약 이 조건이 True라면, ...  

- 형 변환할 때 True, False인지 기억하자.  
    ex) '', None, 0,  ==  False  

In [191]:
# FALSE
print(bool(0))
print(bool(''))
print(bool(None), end='\n\n')

# TRUE
print(bool(1))
print(bool(' '))
print(bool('a'))

False
False
False

True
True
True


ㅤ 
## 3.2 Integer

#### **# 음수 표현**
- 소수점이 없다.
- default는 양수이며, 음수 앞에 -를 붙인다.


In [192]:
a = -10
b = 10
print(a + b)

0


ㅤ
#### **# 리터럴과 0의 위치**
- 리터럴: 값 그 자체, 고정된 값  
    ex) 4  

- 숫자 앞에는 0을 붙일 수 없다.  
    cf) 예외적으로 0bxxx, -> 다른 진수 표현법

In [194]:
number = 0b101010
number

42

In [195]:
number = 03

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (3044983563.py, line 1)

ㅤ  
ㅤ  
#### **# 공백 무시**
- 공백이 많아도 무시가 된다.

In [196]:
a = 3 +           5
a

8

ㅤ  
#### **# 언더바 무시**
- 10,000원 -> 10, 000원 2개로 인식한다.  
- 언더바가 숫자 사이에 있을 경우 언더바가 무시된다.

In [207]:
a,b = 10,000
print(a,b)

a = 10_000
print(a)

10 0
10000


ㅤ 
## 3.3 연산

#### **# 연산의 구성**

- 연산자 (operator):  
ex) +, -, ...  

- 피연산자 (operand):  
ex) 4, 5, ...
- 수식 (expression)

ㅤ   
#### **# 산술연산자, 할당 연산자**

In [224]:
# 할당 연산자
x = 3
y = 4

# 산술 연산자
print(f'+  : {x + y}')
print(f'-  : {x - y}')
print(f'*  : {x * y}')
print(f'/  : {x / y}')

# 거듭제곱 (exponential)
print(f'** : {x ** y}')

# 몫과 나머지 연산
print(f'// : {x // y}')
print(f'%  : {x % y}')    

+  : 7
-  : -1
*  : 12
/  : 0.75
** : 81
// : 0
%  : 3


ㅤ   
- **나눗셈 주의 사항**:
1. 0으로 나누지 않도록 한다. (division by zero)  

In [242]:
3 / 0

ZeroDivisionError: division by zero

ㅤ  
ㅤ2. 나눗셈과 몫 구하는 연산자가 따로 구분되어 있다.

In [249]:
print(5 // 2)
print(5 / 2)
print(5 % 3)

2
2.5
2


In [250]:
divmod(5,3) # 몫, 나머지를 한번에 구할 수도 있다.

(1, 2)

ㅤ   
ㅤ   
#### **# 복합 대입연산자 (Compound Assignment Operator)**

In [238]:
a = b = c = 10
a - 3    # 뺀 결과값을 다시 할당을 하지 않으면 연산 결과값을 사용할 수 없다.


b = b - 3
#1. b - 3 계산
#2. 임시변수 temp = b - 3
#3. b = temp


c -= 3   # 변수 b가 거친 과정과 동일하게 적용이 된다.

print(f'a : {a}, The value of a has not changed')
print(f'b : {b}')
print(f'c : {c}')

a : 10, The value of a has not changed
b : 7
c : 7


- **복합 대입연산자의 종류**:
    - a += 3
    - a -= 3
    - a *= 3
    - a /= 3
    - a ** 3

- **주의할 점:**

In [241]:
unused += 3 # 처음 쓰는 변수라면 초기화 해줘야 한다.

NameError: name 'unused' is not defined

ㅤ 
## 3.4 지수 표현

- e, E 둘다 사용 가능<br>
cf) e앞의 숫자를 10의 지수로 생각하면 편하다.  

- 앞부분은 float, int 모두 가능
- 뒷부분은 int만.
    - 양수면 :0 앞으로
    - 음수면 :0 뒤로 (소수점)

In [255]:
1.0e6 # float

1000000.0

In [256]:
540e-6 

0.00054

In [271]:
5.4e-4

0.00054

ㅤ 
## 3.5 *Review*

### # Quiz 1
- 정수를 입력 받고 3의 배수인지 확인하세요.
- 홀수인지 확인하세요.

In [254]:
number = int(input("숫자를 입력하세요:"))
print(f'3의 배수: {number % 3 == 0}')
print(f'홀수: {number % 2 == 1}')

숫자를 입력하세요: 6


3의 배수: True
홀수: False


  
------

# Ch04. 조건문 if

ㅤ 
## 4.1 코드 작성 방법

#### **# 주석 : 설명하는 부분**

- 목적: 의도를 알아보기 쉽게 표현한다.  
- '#', hash, sharp ...  
- 시작된 부분부터 그 라인 끝까지가 주석  

In [277]:
a = 3 # ;print('Hello')
print(a)

3


- """<주석>"""  → 여러 줄에 걸쳐 주석을 달아야 할 때 사용  
- 문자열 안에 들어있는 해시는 문자열로 인식

In [284]:
"""
주석1
hello!
print('bye')
"""
print('# hello python')

# hello python


ㅤ  
#### **# 라인 유지**

- 들여쓰기 == 공백 4개 == 탭 1개
- 한 줄에 80자를 넘기지 않도록 주의한다.
- 코드가 길어지면 \ 로 끊어준다.

In [285]:
word = 'h' + 'o' + \
    'p' + 'e'
print(word)

hope


ㅤ 
## 4.2 조건문

#### **# Code Structure**

- **조건 1개:**

In [290]:
if '조건':
    pass # 실행할 코드

- **조건 2개:**

In [293]:
if 5 < 3:
    print('Hmm.')
else:
    print('Yes!')

Yes!


- **조건 3개 이상:**

In [294]:
a = 3
if a < 3:
    print('Hmm.')
elif a > 3:
    print('Well..')
else:
    print('Yes!')

Yes!


ㅤ 
## 4.3 비교연산자

- x < y, x <= y
- x > y, x >= y
- x == y (값)
- x != y (값)
- x is y (값, 메모리 주소)
- x is not y

In [297]:
print(3 is 3)

True


<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\skyto\AppData\Local\Temp\ipykernel_4048\380083254.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(3 is 3)


In [302]:
a = [1,2,3]
b = [1,2,3]
print(a is b)

c = b
print(c is b)

False
True


ㅤ 
## 4.4 논리연산자

- 여러 조건식을 비교할 때
- ex) 10 < x < 20
    - 파이썬에서만 가능한 표현
    
    - x > 10 혹은 x < 20
- and, &
    - 둘다 참일 때 True
- or, |
    - 둘 중 하나만 참이여도 True
- not
    - True -> False, False -> True

In [311]:
a = 3
if (2 < a < 4):
    print('a is between 2 and 4', end='\n\n')

a is between 2 and 4



In [313]:
a = 3
b = 5
c = 0

if a == 3 and b == 5:
    print('both numbers are correct.')

if a == 2 or b == 5:
    print('one of the numbers are correct.')
    
if not c:
    print('c is zero')

both numbers are correct.
one of the numbers are correct.
c is zero


ㅤ 
## 4.5 *Review*

### # Quiz 1
- 학점 부여하기
- 학점을 입력 받아서
    - 90점 이상이면 A+,
    - 80, B
    - 70, C
    - 그외, D

In [304]:
testResult = int(input("점수를 입력하세요:"))
grade = 'D'

if testResult >= 90:
    grade = 'A+'
elif testResult >= 80:
    grade = 'B'
elif testResult >= 70:
    grade = 'C'
print(f"학점: {grade}")

점수를 입력하세요: 67


학점: D


ㅤ   
### # Quiz 2
- 아이디와 비번 입력 받아서 둘다 일치하면 로그인하기
- 아이디, 비번 각자 정해놓기
- 일치하지 않을 때에는 창의적으로 어떤 걸로 반환하기

In [308]:
userId = "jw"
password = "1@234"

inputId = input("아이디:")
inputPassword = input("비밀번호:")

if userId == inputId and password == inputPassword:
    print(f"환영합니다 {userId}.")
else:
    if userId != inputId:
        print("아이디가 일치하지 않습니다.")
    elif password != inputPassword:
        print("비밀번호가 일치하지 않습니다.")

아이디: jw
비밀번호: 1@222


비밀번호가 일치하지 않습니다.


ㅤ   
### # Quiz 3.
- 결석 횟수를 받아서 점수가 80점 이상인데 결석이 2번 이상이면 F, 나머지는 점수대로

In [322]:
testResult = int(input("점수를 입력하세요:"))
absent = int(input("결석 횟수:"))
grade = 'D'

if testResult >= 90:
    grade = 'A+'
elif testResult >= 80:
    grade = 'B'
elif testResult >= 70:
    grade = 'C'

if absent >= 2:
    grade = 'F'
print(f"학점: {grade}")

점수를 입력하세요: 69
결석 횟수: 2


학점: F
